/**
 * @file MainMenu.h
 * @brief Defines the MainMenu class, the central hub for navigating to different
 * algorithm visualization modules (sorting, stacks, trees, etc.).
 *
 * This widget manages the views and transitions between the main menu and
 * the various visualizer components.
 */
#ifndef MAINMENU_H
#define MAINMENU_H

#include <QWidget> // @brief Base class for all user interface objects.

namespace Ui {
class MainMenu; // @brief Forward declaration for the UI class generated by Qt Designer.
}

// --- Forward Declarations for Algorithm Visualizer Widgets ---
class SortingVisualizer;        ///< @brief Widget for visualizing sorting algorithms.
class StackVisualizer;          ///< @brief Widget for visualizing stack operations.
class QueueVisualizer;          ///< @brief Widget for visualizing queue operations.
class LinkedListVisualizer;     ///< @brief Widget for visualizing linked list structures.
class TreeVisualizer;           ///< @brief Widget for visualizing tree structures and traversals.
class GraphVisualizer;          ///< @brief Widget for visualizing graph algorithms.
class StringPatternVisualizer;  ///< @brief Widget for visualizing string searching and pattern matching algorithms.

/**
 * @class MainMenu
 * @brief The main entry point and navigation hub for the AlgoVisualizer application.
 *
 * This class handles the initialization and display of all specialized visualizer widgets.
 */
class MainMenu : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the MainMenu widget.
     * @param parent The parent widget (defaulted to nullptr).
     */
    explicit MainMenu(QWidget *parent = nullptr);

    /**
     * @brief Destructor for MainMenu.
     */
    ~MainMenu();

private slots:
    // --- Card Click Handlers (Navigate to Visualizer) ---

    /** @brief Handles navigation to the Sorting Visualizer. */
    void on_sortingCard_clicked();

    /** @brief Handles navigation to the Stack Visualizer. */
    void on_stackCard_clicked();

    /** @brief Handles navigation to the Queue Visualizer. */
    void on_queueCard_clicked();

    /** @brief Handles navigation to the Linked List Visualizer. */
    void on_linkedListCard_clicked();

    /** @brief Handles navigation to the Tree Visualizer. */
    void on_treeCard_clicked();

    /** @brief Handles navigation to the Graph Visualizer. */
    void on_graphCard_clicked();

    /** @brief Handles navigation to the String Pattern Visualizer. */
    void on_stringCard_clicked();

    // --- Back Button Handlers (Navigate back to Main Menu) ---

    /** @brief Handles the 'Back to Menu' signal from the Sorting Visualizer. */
    void on_backButtonSorting_clicked();

    /** @brief Handles the 'Back to Menu' signal from the Stack Visualizer. */
    void on_backButtonStack_clicked();

    /** @brief Handles the 'Back to Menu' signal from the Queue Visualizer. */
    void on_backButtonQueue_clicked();

    /** @brief Handles the 'Back to Menu' signal from the Linked List Visualizer. */
    void on_backButtonLinkedList_clicked();

    /** @brief Handles the 'Back to Menu' signal from the Tree Visualizer. */
    void on_backButtonTree_clicked();

    /** @brief Handles the 'Back to Menu' signal from the Graph Visualizer. */
    void on_backButtonGraph_clicked();

    /** @brief Handles the 'Back to Menu' signal from the String Visualizer. */
    void on_backButtonString_clicked();

private:
    Ui::MainMenu *ui; ///< @brief Pointer to the UI object generated by Qt Designer.

    /**
     * @brief Switches the application view back to the main menu page.
     */
    void showMenuPage();

    // --- Pointers to Visualizer Instances ---

    SortingVisualizer *m_sortingVisualizer;
    StackVisualizer *m_stackVisualizer;
    QueueVisualizer *m_queueVisualizer;
    LinkedListVisualizer *m_linkedListVisualizer;
    TreeVisualizer *m_treeVisualizer;
    GraphVisualizer *m_graphVisualizer;
    StringPatternVisualizer *m_stringVisualizer;
};

#endif // MAINMENU_H
