/**
 * @file StartScreen.h
 * @brief Defines the StartScreen class, the initial widget displayed when the application launches.
 *
 * This screen typically contains a welcoming message and a button to proceed
 * to the MainMenu, acting as the entry point into the visualizer application.
 */
#ifndef STARTSCREEN_H
#define STARTSCREEN_H

#include <QWidget> // @brief Base class for all user interface objects.

namespace Ui {
class StartScreen; // @brief Forward declaration for the UI class generated by Qt Designer.
}

/**
 * @class StartScreen
 * @brief The initial landing page of the application.
 *
 * It manages the simple UI (like a 'Start' button) and transitions the user
 * to the MainMenu when the interaction is complete.
 */
class StartScreen : public QWidget
{
    Q_OBJECT

public:
    /**
     * @brief Constructs the StartScreen widget.
     * @param parent The parent widget (defaulted to nullptr).
     */
    explicit StartScreen(QWidget *parent = nullptr);

    /**
     * @brief Destructor for StartScreen.
     */
    ~StartScreen();

private slots:
    /**
     * @brief Handles the click event of the main 'Start' button in the UI.
     *
     * This slot is typically connected to show the MainMenu and hide the StartScreen.
     */
    void on_startButton_clicked();

private:
    Ui::StartScreen *ui; ///< @brief Pointer to the UI object generated by Qt Designer.
};

#endif // STARTSCREEN_H
